version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "glacierrestore"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hjuxmhfd2ufd"
s3_prefix = "glacierrestore"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
